# Generated by Django 2.2 on 2019-05-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='debug-post'),
            preserve_default=False,
        ),
    ]
